"""empty message

Revision ID: 06dde3a5c480
Revises: 2406ac435f17
Create Date: 2020-11-29 22:07:21.860149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dde3a5c480'
down_revision = '2406ac435f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('date', sa.String(length=20), nullable=False))
    op.drop_constraint('Shows_venue_id_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_artist_id_fkey', 'Shows', type_='foreignkey')
    op.drop_column('Shows', 'show_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('show_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key('Shows_artist_id_fkey', 'Shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key('Shows_venue_id_fkey', 'Shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Shows', 'date')
    # ### end Alembic commands ###
