"""empty message

Revision ID: 3e3a68057fdd
Revises: 06dde3a5c480
Create Date: 2020-11-29 22:33:34.138460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3a68057fdd'
down_revision = '06dde3a5c480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('show_date', sa.String(length=20), nullable=False))
    op.drop_column('Shows', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('date', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('Shows', 'show_date')
    # ### end Alembic commands ###
